<?php
require_once __DIR__ . '/../config/database.php'; require_once __DIR__ . '/../includes/functions.php'; requireLogin(); $userId=(int)$_SESSION['user_id']; $message='';$error='';
$res=$conn->query("SELECT * FROM user_checklists WHERE user_id={$userId} ORDER BY id DESC LIMIT 1"); $checklist=$res?$res->fetch_assoc():null; if(!$checklist){$conn->query("INSERT INTO user_checklists (user_id,nama_checklist,status_checklist) VALUES ({$userId},'Checklist Pendakian Default','aktif')"); $res=$conn->query("SELECT * FROM user_checklists WHERE user_id={$userId} ORDER BY id DESC LIMIT 1"); $checklist=$res?$res->fetch_assoc():null; $newId=(int)($checklist['id']??0); if($newId>0){$conn->query("INSERT INTO user_checklist_items (checklist_id, equipment_item_id, prioritas, urutan) SELECT {$newId}, id, prioritas, 1 FROM equipment_items WHERE is_default = 1");} } $checklistId=(int)($checklist['id']??0);
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['toggle_item'])){ $itemId=(int)$_POST['item_id']; $new=(int)$_POST['new_status']; $stmt=$conn->prepare('UPDATE user_checklist_items SET is_packed=? WHERE id=? AND checklist_id=?');$stmt->bind_param('iii',$new,$itemId,$checklistId);$stmt->execute(); header('Location: '.pageUrl('checklist')); exit; }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['add_custom'])){ $nama=trim($_POST['nama_item_custom']??'');$berat=(float)($_POST['berat_kg']??0); if($nama!==''){ $stmt=$conn->prepare('INSERT INTO user_checklist_items (checklist_id,nama_item_custom,berat_kg,prioritas,urutan) VALUES (?,?,?,"optional",99)');$stmt->bind_param('isd',$checklistId,$nama,$berat);$stmt->execute(); $message='Item berhasil ditambahkan.'; }}
$items=[]; if($q=$conn->query("SELECT uci.*,COALESCE(ei.nama_item,uci.nama_item_custom) nama_item,COALESCE(uci.deskripsi_item,ei.deskripsi_singkat) deskripsi_item,COALESCE(uci.berat_kg,ei.berat_kg) berat_final,COALESCE(ec.nama_kategori,'Custom') nama_kategori,ec.icon_name FROM user_checklist_items uci LEFT JOIN equipment_items ei ON ei.id=uci.equipment_item_id LEFT JOIN equipment_categories ec ON ec.id=ei.category_id WHERE uci.checklist_id={$checklistId} ORDER BY ec.urutan,uci.urutan")){while($r=$q->fetch_assoc())$items[]=$r;} $packed=0;$weight=0; foreach($items as $it){$packed+=(int)$it['is_packed'];$weight+=(float)$it['berat_final'];} $pageTitle='Checklist Perlengkapan';$currentPage='checklist'; include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/layout_top.php';
?>
<div class="grid xl:grid-cols-[1fr_380px] gap-6">
  <div class="editorial-card p-8"><div class="flex flex-wrap justify-between gap-4 mb-8"><div><p class="uppercase tracking-[.3em] text-on-surface-variant text-xs font-bold">Gear Management</p><h3 class="text-3xl font-extrabold mt-2"><?=e($checklist['nama_checklist']??'Checklist')?></h3><p class="text-on-surface-variant mt-2">Centang perlengkapan yang sudah siap sebelum berangkat.</p></div><div class="grid grid-cols-3 gap-3 text-center"><div class="editorial-card-soft px-5 py-4"><b class="text-2xl text-primary"><?=count($items)?></b><p class="text-xs text-on-surface-variant">Item</p></div><div class="editorial-card-soft px-5 py-4"><b class="text-2xl text-primary"><?=$packed?></b><p class="text-xs text-on-surface-variant">Packed</p></div><div class="editorial-card-soft px-5 py-4"><b class="text-2xl text-primary"><?=number_format($weight,1)?></b><p class="text-xs text-on-surface-variant">Kg</p></div></div></div><?php if($message):?><div class="mb-6 bg-green-100 text-green-800 rounded-xl px-4 py-3"><?=e($message)?></div><?php endif;?><div class="space-y-4"><?php if($items): foreach($items as $it):?><div class="editorial-card-soft p-5 flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div class="flex gap-4"><div class="w-12 h-12 rounded-2xl bg-white flex items-center justify-center text-primary"><span class="material-symbols-outlined"><?=e($it['icon_name']?:'inventory_2')?></span></div><div><h4 class="font-extrabold text-lg <?=((int)$it['is_packed']===1)?'line-through text-on-surface-variant':''?>"><?=e($it['nama_item'])?></h4><p class="text-sm text-on-surface-variant"><?=e($it['nama_kategori'])?> • <?=e($it['prioritas'])?> • <?=number_format((float)$it['berat_final'],2)?> kg</p><p class="text-sm text-on-surface-variant mt-1"><?=e($it['deskripsi_item'])?></p></div></div><form method="POST"><input type="hidden" name="toggle_item" value="1"><input type="hidden" name="item_id" value="<?= (int)$it['id']?>"><input type="hidden" name="new_status" value="<?=((int)$it['is_packed']===1)?0:1?>"><button class="<?=((int)$it['is_packed']===1)?'bg-green-100 text-green-800':'bg-amber-100 text-amber-800'?> rounded-2xl px-5 py-3 font-bold"><?=((int)$it['is_packed']===1)?'Sudah Packed':'Belum Packed'?></button></form></div><?php endforeach; else:?><p class="text-on-surface-variant">Belum ada item checklist.</p><?php endif;?></div></div>
  <div class="space-y-6"><div class="editorial-card p-6"><h3 class="text-xl font-extrabold mb-4">Tambah Item Custom</h3><form method="POST" class="space-y-4"><input type="hidden" name="add_custom" value="1"><input name="nama_item_custom" class="w-full rounded-2xl bg-surface-variant/40 border-0 px-4 py-3" placeholder="Nama item"><input type="number" step="0.01" name="berat_kg" class="w-full rounded-2xl bg-surface-variant/40 border-0 px-4 py-3" placeholder="Berat kg"><button class="btn-primary w-full">Tambah Item</button></form></div><div class="editorial-card p-6"><h3 class="text-xl font-extrabold mb-3">Progress</h3><div class="h-3 rounded-full bg-surface-variant overflow-hidden"><div class="h-full bg-primary" style="width:<?=count($items)?round($packed/count($items)*100):0?>%"></div></div><p class="mt-3 text-sm text-on-surface-variant"><?=$packed?> dari <?=count($items)?> item sudah siap.</p></div></div>
</div>
<?php include __DIR__.'/../includes/layout_bottom.php'; include __DIR__.'/../includes/footer.php'; ?>
